### ISSUE TITLE
Collection.Mapping deprecated for python +3.10

### ISSUE THREAD

**Issue by hyper750** [mattupstate/flask-jwt#144]
When trying to use flask-jwt with a python version +3.10 (just importing `jwt`) returns an error, when trying to import collection.Mapping. Is using it inside the following files:

- api_jwt.py
- api_jws.py

For the version of python 3.9 only shows a warning when trying to import it:

```python
from collections import Mapping

<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
```

For the version of python +3.10 the import should be change to the following

```python
from collections.abc import Mapping
```

**Comment by tirkarthi** [comment]
This seems to have been fixed in pyjwt which probably needs an update : https://github.com/jpadilla/pyjwt/commit/30d4c5a7f91e2425211b51c479f2f1e7a37f98b9
