### ISSUE TITLE
Can JWTs be assigned without going to /auth?

### ISSUE THREAD

**Issue by sureshjoshi** [mattupstate/flask-jwt#36]
I've switched over all of my auth mechanisms to use JWTs across the board, but there is one workflow that would be great if there was an easy way to spit out a JWT from the library. 

In my user registration workflow, they fill in their data, I add them to the database (after validation), I send them a confirmation mail, but now I'm requiring them to re-login to go through the @jwt_required workflow so I can return a JWT. 

After registration, I want them to log in directly, so is there a way to extract a JWT (given that they just gave me their username/pass), without having to re-encode them manually?

Thanks!
-SJ

**Comment by mattupstate** [comment]
```python
from flask_jwt import generate_token

user = ... get your user object ...

jwt = generate_token(user)
```

**Comment by sureshjoshi** [comment]
Ah geez, that's embarrassing....   :)

For some reason, I was looking at these docs: https://pythonhosted.org/Flask-JWT/_modules/flask_jwt.html#JWT.error_handler  instead of on Github, which shows generate token, plain as day!

Thanks Matt!

**Comment by sureshjoshi** [comment]
Is there any reason this last fix isn't in the pip repo? I'm pulling down 0.2.0 as far as I can tell, and generate token doesn't exist.

**Comment by sureshjoshi** [comment]
Just to ping this one again, will the latest Git code be pushed to the global repo so pip install will find it? I can't seem to get pip to git pull, for the life of me.
