### ISSUE TITLE
Issue when combined with Flask-restful Resource classes?

### ISSUE THREAD

**Issue by jonny166** [mattupstate/flask-jwt#37]
Hi, I was having good luck with your package so far, but when I tried to integrate it with my Flask-restful resource classes, I ran into issues. Is there a way to use this decorator with Resource classes?  Here is a code snippet and error.  Thanks!

class Events(Resource):
    @marshal_with(eventFields, envelope="events")
    @jwt_required
    def get(self):
        return events.values()

Traceback (most recent call last):
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 431, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 521, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 613, in wrapper
    resp = f(*args, **kwargs)
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/site-packages/flask_jwt/__init__.py", line 85, in wrapper
    @wraps(fn)
  File "/opt/iat/IaT5.1/usr/local/lib/python2.7/functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'Events' object has no attribute '__name__'

**Comment by sureshjoshi** [comment]
Hi, I'm using Flask-Classy, rather than Flask-Restful, but have you tried using the 'method_decorators'

    class Events(Resource):
         method_decorators = [jwt_required()]

**Comment by jonny166** [comment]
Thanks!!  That fixed it.

However, now when those methods are called and the token is missing, invalid, or expired, it raises a JWTError and returns 500 "Internal Server Error".

I tried adding my own error_handler function with the @jwt.error_handler decorator, but that didn't seem to help as it wasn't being called when the errors were thrown.  In any case, I think the default _error_callback function should be sufficient to return the desired 400 code instead of 500.  

Any ideas what I might have misconfigured that is causing the error callback function to not be called?

Thanks!

**Comment by sureshjoshi** [comment]
Well, not to take this too far off the main issue's track... Do you have sample code snippets? Also, are you using the most recent code? Not the one from Pip, but rather the latest code in Github? 

For example, I call http://localhost:5000/api/v1/users
Without an Authorization header of any kind, and I get this (which is what I wanted):

{
    "description": "Authorization header was missing",
    "error": "Authorization Required",
    "status_code": 401
}

If I add 'Authorization: JWT sdaskdksaljds'
I get:

{
    "description": "Token is undecipherable",
    "error": "Invalid JWT",
    "status_code": 400
}

**Comment by sureshjoshi** [comment]
Additional context: https://github.com/flask-restful/flask-restful/issues/372

**Comment by jonny166** [comment]
Thanks for the help.  Flask-Restful was hijacking the errors.  I figured out a good work around.  I overrode the flask-restful error_router method to defer to the original handler for Flask-JWT errors.

**I replaced this line in my code:**
```python
api = Api(app)
```
**With the following**
```python
class ErrorFriendlyApi(Api):
    def error_router(self, original_handler, e):
        if type(e) is JWTError:
            return original_handler(e)
        else:
            return super(ErrorFriendlyApi, self).error_router(original_handler, e)

api = ErrorFriendlyApi(app)#, errors=errors)
```

**Comment by rchampa** [comment]
Hi @jonny166 I'm trying your code but e is always a KeyError type and never JWTError. Did you have an extra setup that I could miss? 
I want JWTError because I would like the reason of error.

**Comment by jonny166** [comment]
Not sure I follow.  The wrapper class is just designed to let the JWTErrors fall through Flask-Restful.  You still have to define handlers for them using the @jwt.error_handler decorator.  

If you have KeyErrors that you need to allow to fall through Flask-Restful as well, then you could add another case in the Api wrapper class like I did for JWTError.  But I suspect you might be better off handling them where they occur.

**Comment by rchampa** [comment]
I have already try with and without @jwt.error_handler decorator.

@jwt.error_handler
def error_handler(e):
    data =  {
                "code":e.status_code,
                "message":e.error+" "+e.description
            }
    return jsonify(data), 400

**Comment by jonny166** [comment]
What does your wrapper class look like and what error are you getting?

**Comment by rchampa** [comment]
This is what i have already try http://stackoverflow.com/questions/33083105/flask-jwt-and-flask-resftul-error-handling

I'm trying to share code though github.

**Comment by rchampa** [comment]
My jwt implementation https://github.com/rchampa/timetable/blob/master/my_jwt/my_jwt_setup.py
My restful implementation https://github.com/rchampa/timetable/blob/master/my_flask_restful/FlaskRestfulJwtAPI.py
My api https://github.com/rchampa/timetable/blob/master/restful/users.py

**Comment by aguegu** [comment]
Thanks @rchampa .

I have got a simpler example for this: 

https://stackoverflow.com/questions/34217728/flask-restful-api-authorization/36169320#36169320
