### ISSUE TITLE
exp claim in header rather than body ?

### ISSUE THREAD

**Issue by harmon25** [mattupstate/flask-jwt#40]
Have had great success using this library with angular-jwt... until attempting to implement client side token expiry notifications...
the angular-jwt module has a function to check if a token is expired, it is looking in the JWT body for the exp claim - however it appears flask-jwt is writing the exp and iat to the JWT header by default? 

Am I doing something wrong? or should the exp and iat be contained within the body?

Any help would be great, thanks!

**Comment by harmon25** [comment]
Have managed to work around this by placing the exp formatted as time since epoch in the payload of the token. 

It is not well documented but I believe the representation of dates in a JWT should be time since epoch...

There may be a better way of accomplishing this but the following is what I am using

```python
@jwt.payload_handler
def make_payload(user):
    expiry = (datetime.now() - datetime.fromtimestamp(0)) + app.config['JWT_EXPIRATION_DELTA']
    return {
        'user_id': user.id,
        'exp': int(expiry.total_seconds())
            }
```

**Comment by sureshjoshi** [comment]
Hey @harmon25 , this isn't a Flask-JWT issue, but rather the underlying itsdangerous library. I ran into the same problem you did, but I'm using Satellizr

This issue is documented here: https://github.com/mitsuhiko/itsdangerous/pull/19

I think I had basically the same workaround, but I also added an iat tag.

    iat = calendar.timegm(datetime.utcnow().timetuple())
    exp = calendar.timegm((datetime.utcnow() + current_app.config['JWT_EXPIRATION_DELTA']).timetuple())
    return {
        'user_id': user.id,
        'iat': iat,
        'exp': exp
    }

**Comment by harmon25** [comment]
thanks joshi for confirming that for me, had a hunch it was related to itsdangerous.
Your solution is a bit more elegant than mine, will likely implement the kludge that way :+1:
