### ISSUE TITLE
Misunderstanding of the difference between JWS and JWT

### ISSUE THREAD

**Issue by ptxmac** [mattupstate/flask-jwt#41]
Internally Flask-JWT are using the TimedJSONWebSignatureSerializer from its dangerous. Unfortunately this ISN'T a JWT generator. Instead it creates a JWS with some extra information in the header like 'exp'.

According to the JWT specification, all the claims are supposed to be part of the payload NOT the header. (They are allowed to be replicated in the header, but not if omitted in the payload)

This seems to me as quite a big misunderstanding of the specification and should be rectified

**Comment by mattupstate** [comment]
Yeah, I'm aware. I was a bit naive when I first wrote this. It's something that I want to address, but admittedly I've been having a hard time finding time to dedicate to open source lately.

**Comment by ptxmac** [comment]
I currently have a use for JWT in a work-related flask project, so I might have a good opportunity to make changes and give them back to this project. I though it might be relevant to take a look at pyjwt as the base. It seems to be well supported, and is the "official" suggestion for python on http://jwt.io

**Comment by rlam3** [comment]
@ptxmac 

I used the following workaround for the payload/claim... is this sufficient?

    @jwt.payload_handler
    def make_payload(user):
        data = dict()
        data["user_id"] = user.id
        datetimenow = datetime.now()
        data["nbf"] = time.mktime(datetimenow.timetuple())
        expiration = datetimenow + current_app.config['JWT_EXPIRATION_DELTA']
        data["exp"] = time.mktime(expiration.timetuple())
        return data

**Comment by harmon25** [comment]
@rlam3
yea that works - a bit faster to just directly return a dictionary. 
```py
@jwt.payload_handler
def make_payload(user):
    expiration = datetimenow + current_app.config['JWT_EXPIRATION_DELTA']
    datetimenow = datetime.now()
    return {'user_id': user.id,
            'exp': time.mktime(expiration.timetuple()),
            'nbf': time.mktime(datetimenow.timetuple())}
```

**Comment by bangive** [comment]
please you fix this soon

**Comment by minhoryang** [comment]
+1 to all awesome guys in here!!

**Comment by mattupstate** [comment]
For all interested parties, please review the [pwjwt branch](https://github.com/mattupstate/flask-jwt/tree/pyjwt)

**Comment by jarmani** [comment]
Looks good at first glance, but I'm not fan of the user => identity renaming.

**Comment by mattupstate** [comment]
@jarmani lately I feel like `identity` is a better, abstract, word than `user` because tokens don't necessarily represent a user in every application.

**Comment by dorianpula** [comment]
@mattupstate Just to follow-up, is this still an issue with the latest release 0.3.0? (I'm hoping I can use that instead of using the pyjwt branch.)

**Comment by rlam3** [comment]
@dorianpula +1

**Comment by mattupstate** [comment]
This has been addressed in the new release. I should have deleted the pyjwt
branch after I released it.

**Comment by dorianpula** [comment]
@mattupstate Thanks for getting back so quickly and fixing the issue!
