### ISSUE TITLE
UnboundLocalError if JWT_VERIFY_EXPIRATION is False

### ISSUE THREAD

**Issue by lustdante** [mattupstate/flask-jwt#43]
```
def _default_decode_handler(token):
    """Return the decoded token."""
    try:
        result = _get_serializer().loads(token)
    except SignatureExpired:
        if current_app.config['JWT_VERIFY_EXPIRATION']:
            raise
    return result
```

Even if not checking expiration is not recommended, it should still be an option, but since timed serializer will not deserialize, it raises:

```
UnboundLocalError: local variable 'result' referenced before assignment
```

**Comment by maangulo12** [comment]
+1
I am having the same issue.

**Comment by mattupstate** [comment]
Care to upgrade and see if this is still a problem? Bear in mind there are some breaking changes, so please refer to the docs.
