### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by mayantigo** [mattupstate/flask-jwt#58]
Hi!.

Im running exactly the example of GitHub. When I try get the token the log tell me this:

  File "C:\Python34\lib\site-packages\flask_jwt\__init__.py", line 114, in _def
ult_auth_request_handler
    username = data.get(current_app.config.get('JWT_AUTH_USERNAME_KEY'), None)
AttributeError: 'NoneType' object has no attribute 'get'

Im checking the code and I see nothing
Is exactly the same code of the example.

Any suggestion?.

**Comment by mattupstate** [comment]
You are most likely sending an incorrect HTTP request to your server. Make sure the `Content-Type` header is set to a JSON content type like `application/json` and make sure the request body is a JSON formatted string.

**Comment by mayantigo** [comment]
That is exactly what is happening.

Thank you very much!.

**Comment by xcixor** [comment]
has to be JSON(application/json)

**Comment by Poovendranavs** [comment]
can anyone guide me how to build Bulk upload request and get output in Postman.

**Comment by Vishal1309** [comment]
@mayantigo do you remember how exactly did you deal with this error? I cannot figure out the solution here
